dist: xenial

language: scala

scala:
   - 2.13.1
   - 2.12.11

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_deploy:
  # Record minimal build information via the Git user ident
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  # Decrypt the secret deploy key using instructions from `travis encrypt-file`
  #- openssl aes-256-cbc -K $encrypted_3afbfedfa397_key -iv $encrypted_3afbfedfa397_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  #- chmod 600 project/travis-deploy-key
  # Start ssh-agent in the background and load the deploy key
  #- eval "$(ssh-agent -s)"
  #- ssh-add project/travis-deploy-key  

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

install:
  - pip install --user codecov
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5  
  - gem install asciidoctor

script:
#  - sbt clean coverage test 
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION  clean coverage test coverageReport && bash <(curl -s https://codecov.io/bash);
    else 
      sbt ++$TRAVIS_SCALA_VERSION  clean test makeSite && echo "Skipping code coverage reporting and docs on 2.13";
    fi  

jdk:
  - oraclejdk12
  - openjdk12

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: target/site
  on:
    branch: master
    condition: $TRAVIS_SCALA_VERSION = 2.13.1 